name: bZone
main: com.bradsproject.BradleyJewell.bZone.bZone
version: 1.1.1
description: Control independent zones of your world!
authors:
  - Brad811
commands:
  zone:
    description: Get the name of your current zone.
    usage: /<command>